---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Moderne Kunst
description: Programmeer je eigen computergemaakte kunst.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Willekeurige kleuren
  - 
    title: Willekeurige plek
  - 
    title: 'Uitdaging: schildpaddenkunst'
  - 
    title: Maak rechthoekige moderne kunst
  - 
    title: 'Uitdaging: meer moderne kunst'
