---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Modern Art
description: Code your own computer-generated modern art.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2025-01-03
steps:
- title: What you will make
- title: Random colours
- title: Random place
  completion:
  - engaged
- title: 'Challenge: Turtle art'
  challenge: true
- title: Create rectangle modern art
  completion:
  - internal
- title: 'Challenge: More modern art'
  challenge: true
