---
hero_image: images/banner.png
theme: ljubičasta
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Moderna umjetnost
description: Napiši program kojim ćeš pomoću računala napraviti modernu umjetnost.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: umjetnost
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Nasumične boje
- title: Nasumična pozicija
  completion:
  - engaged
- title: 'Izazov: kornjačina umjetnost'
- title: Kreiraj modernu umjetnost s pravokutnicima
  completion:
  - internal
- title: 'Izazov: još moderne umjetnosti'
