---
hero_image: images / banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, 디자인 -0, 프로그래밍 -1, phys-comp-0, 제조 -0, 커뮤니티 -0
title: Modern Art
description: Code your own computer-generated modern art.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: Random colours
  - 
    title: Random place
  - 
    title: 'Challenge: Turtle art'
  - 
    title: Create rectangle modern art
  - 
    title: 'Challenge: More modern art'
