---
hero_image: images / banner.png
theme: fioletowy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Sztuka współczesna
description: Koduj swoją własną sztukę generowaną komputerowo.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: pyton
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Losowe kolory
  - 
    title: Losowe miejsce
  - 
    title: 'Wyzwanie: Sztuka żółwia'
  - 
    title: Twórz prostokąt sztuki nowoczesnej
  - 
    title: 'Wyzwanie: bardziej nowoczesna sztuka'
