---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Moderna umjetnost
description: Kodiraj svoju modernu umjetnost koju generiše računar.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Nasumične boje
  - 
    title: Nasumična pozicija
  - 
    title: 'Izazov: Kornjačina umjetnost'
  - 
    title: Kreiraj modernu umjetnost sa pravougaonicima
  - 
    title: 'Izazov: Još moderne umjetnosti'
