---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Art moderne
description: Code ton propre oeuvre d'art moderne assisté par ordinateur.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Couleurs aléatoires
  - 
    title: Emplacement aléatoire
  - 
    title: 'Défi : Art tortuesque'
  - 
    title: Créer de l'art moderne rectangulier
  - 
    title: 'Défi : Plus d''art moderne'
