---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Arte Moderna
description: Codifica la tua arte moderna creata al computer.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Colori casuali
  - 
    title: Posizione casuale
  - 
    title: 'Sfida: Arte di tartaruga'
  - 
    title: Crea arte moderna rettangolare
  - 
    title: 'Sfida: Altra arte moderna'
