---
hero_image: images/banner.png
theme: menekşe
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Modern Sanat
description: Kendi bilgisayar destekli çağdaş sanat eserinizi kodlayın.
original_url: https://codeclubprojects.org/en-GB/python/modern-art
interests: sanat
technologies: python
site_areas: projeler
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Rastgele renkler
  - 
    title: Rastgele yer
  - 
    title: 'Meydan Okuma: Turtle modül sanatı'
  - 
    title: Dikdörtgen modern sanat yaratın
  - 
    title: 'Meydan Okuma: Daha fazla modern sanat'
